services:
  - type: web
    name: n8n-mcp
    env: docker
    repo: https://github.com/kailee83/n8n-render-mcp
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "password"
      - key: N8N_CUSTOM_EXTENSIONS
        value: /data/custom

      - key: GENERIC_TIMEZONE
        value: Asia/Singapore
      - key: N8N_HOST
        value: 0.0.0.0

