services:
  - type: web
    name: n8n-db
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_URL
        fromDatabase:
          name: n8n-db
          property: connectionString
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: N8N_METRICS
        value: false
